pipeline {

	agent any

	tools{
		nodejs '19.6.0'
	}

	stages {

		stage("build") {

			steps {
				echo '[BUILDING] Building the application'
				sh 'npm install && npm run build'

				sh 'ls dist/'
			}
		}

		stage("deploy") {

			steps {
				echo '[DEPLOYING] Deploying the application'

				withCredentials([usernamePassword(credentialsId: 'Homepage-Server', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
					script {
						def remote = [:]
						remote.name = 'Homepage'
						remote.host = "${env.IONOS_WEBSITE_HOSTNAME}"
						remote.user = USER
						remote.port = 22
						remote.password = PASS
						remote.allowAnyHosts = true
						sshCommand remote: remote, command: "rm -r ./assets || true"
						sshPut remote: remote, from: './dist/.', into: '.'
					}
				}
			}
		}
		stage("clean up") {

			steps {
				echo '[MOVING] Move files to root folder and delete empty dist folder'

				withCredentials([usernamePassword(credentialsId: 'Homepage-Server', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
					script {
						def remote = [:]
						remote.name = 'Homepage'
						remote.host = "${env.IONOS_WEBSITE_HOSTNAME}"
						remote.user = USER
						remote.port = 22
						remote.password = PASS
						remote.allowAnyHosts = true
						sshCommand remote: remote, command: "ls -a"
						sshCommand remote: remote, command: "mv ./dist/* . &&  rmdir ./dist/"
					}
				}
			}
		}
	}
}