on: push
name: 🚀 Deploy website on push
jobs:
    build:
        name: 🛠️ Build
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v3

            - name: 🖥️ Setup Node.js 17.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - run: |
                  npm ci
                  npm run build --if-present

            - name: ⏫ Archive production artifact
              uses: actions/upload-artifact@v3
              with:
                  name: stevenzieske.de-dist
                  path: dist/
                  retention-days: 1

    deploy:
        name: 🚀 Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: ⏬ Download production artifact from Build job
              uses: actions/download-artifact@v3
              with:
                  name: stevenzieske.de-dist

            - name: 🌌 Sync files
              uses: sand4rt/ftp-deployer@v1.7
              with:
                  sftp: true
                  host: ${{ secrets.IONOS_SFTP_SERVER }}
                  port: 22
                  username: ${{ secrets.IONOS_SFTP_USERNAME }}
                  password: ${{ secrets.IONOS_SFTP_PASSWORD }}

                  local_folder: ./
                  cleanup: true
                  include: '["*", "**/*", ".*"]'
