on: push
name: 🚀 Deploy website on push
jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v3

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: ${{ secrets.IONOS_SFTP_SERVER }}
                  username: ${{ secrets.IONOS_SFTP_USERNAME }}
                  password: ${{ secrets.IONOS_SFTP_PASSWORD }}
                  protocol: ftps
                  port: 22
                  dry-run: true
