on: push
name: 🚀 Deploy website on push
jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v3
            - name: Use Node.js 17.x
              uses: actions/setup-node@v1
              with:
                  node-version: 17.x
            - run: npm install
            - run: npm run build --if-present

            - run: chmod -R 755 dist/assets
            - run: chmod -R 755 dist/publicAssets
            - run: chmod -R 644 dist/index.html

            - name: 📂 Sync files
              uses: sand4rt/ftp-deployer@v1.7
              with:
                  sftp: true
                  host: ${{ secrets.IONOS_SFTP_SERVER }}
                  port: 22
                  username: ${{ secrets.IONOS_SFTP_USERNAME }}
                  password: ${{ secrets.IONOS_SFTP_PASSWORD }}

                  local_folder: dist
                  remote_folder: public
                  cleanup: true
                  include: '["*", "**/*", ".*"]'
